import { useState } from 'react';
import axios from 'axios';
import { Upload, FileUp, Activity, AlertTriangle, CheckCircle, Download, Save } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from "jspdf";

const ScanPage = () => {
    const [file, setFile] = useState(null);
    const [preview, setPreview] = useState(null);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);
    const [error, setError] = useState(null);

    const handleFileChange = (e) => {
        const selectedFile = e.target.files[0];
        if (selectedFile) {
            setFile(selectedFile);
            setPreview(URL.createObjectURL(selectedFile));
            setResult(null);
            setError(null);
        }
    };

    const handleScan = async () => {
        if (!file) return;

        setLoading(true);
        setError(null);

        const formData = new FormData();
        formData.append('file', file);
        // Hardcoded patient ID for demo, real app would select patient
        const patientId = 1;

        try {
            const response = await axios.post(`/scans/predict?patient_id=${patientId}`, formData, {
                headers: {
                    'Content-Type': 'multipart/form-data',
                },
            });
            setResult(response.data);
        } catch (err) {
            console.error(err);
            setError("Failed to process scan. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadReport = async () => {
        if (!result) return;

        const doc = new jsPDF();

        // Add Header
        doc.setFillColor(10, 20, 30); // Dark background
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("NeuroScan Diagnostic Report", 20, 25);

        // Add Content
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 55);

        doc.setFontSize(16);
        doc.text("Analysis Result:", 20, 70);

        doc.setFontSize(14);
        doc.setTextColor(50, 50, 50);
        doc.text(`Diagnosis: ${result.diagnosis}`, 20, 85);
        doc.text(`Confidence Score: ${(result.confidence * 100).toFixed(2)}%`, 20, 95);

        doc.setDrawColor(200, 200, 200);
        doc.line(20, 105, 190, 105);

        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text("Clinical Note:", 20, 115);
        doc.text("This result is generated by an AI model (ViT-Base) and should be", 20, 125);
        doc.text("verified by a certified radiologist.", 20, 132);

        doc.save(`NeuroScan_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
    };

    const handleSaveHistory = async () => {
        // In this implementation, the backend ALREADY saves the scan during prediction.
        // So we just need to notify the user.
        // If we wanted to add extra "notes" we would need a separate endpoint.
        alert("Scan automatically saved to patient history.");
    };

    const getConfidenceColor = (conf) => {
        if (conf > 0.9) return 'bg-green-500';
        if (conf > 0.7) return 'bg-yellow-500';
        return 'bg-red-500';
    };

    return (
        <div className="p-8">
            <h1 className="text-3xl font-bold mb-8 text-white flex items-center gap-3">
                <Activity className="text-neuro-400" />
                New MRI Analysis
            </h1>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Upload Section */}
                <div className="glass-panel p-8 rounded-2xl relative overflow-hidden group">
                    <div className="border-2 border-dashed border-neuro-700/50 rounded-xl h-96 flex flex-col items-center justify-center relative transition-colors hover:border-neuro-500/50">
                        {preview ? (
                            <div className="relative w-full h-full">
                                <img src={preview} alt="MRI Scan" className="w-full h-full object-contain rounded-lg" />
                                {loading && (
                                    <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                                        <div className="w-full h-1 bg-neuro-500/50 absolute top-0 animate-scan-beam shadow-[0_0_15px_#2dd4bf]"></div>
                                    </div>
                                )}
                            </div>
                        ) : (
                            <div className="text-center p-6">
                                <Upload className="w-16 h-16 text-neuro-600 mb-4 mx-auto" />
                                <p className="text-gray-400 mb-2">Drag and drop MRI scan here</p>
                                <p className="text-xs text-gray-600">DICOM, JPG, PNG supported</p>
                            </div>
                        )}

                        <input
                            type="file"
                            onChange={handleFileChange}
                            className="absolute inset-0 w-full h-full opal-0 cursor-pointer opacity-0"
                        />
                    </div>

                    <button
                        onClick={handleScan}
                        disabled={!file || loading}
                        className={`mt-6 w-full py-4 rounded-xl font-bold text-lg transition-all flex items-center justify-center gap-2
                ${!file || loading
                                ? 'bg-gray-800 text-gray-500 cursor-not-allowed'
                                : 'bg-neuro-600 hover:bg-neuro-500 text-white shadow-lg shadow-neuro-500/20'
                            }`}
                    >
                        {loading ? (
                            <>
                                <Activity className="animate-spin" />
                                Analyzing Neural Structures...
                            </>
                        ) : (
                            <>
                                <FileUp />
                                Start Analysis
                            </>
                        )}
                    </button>
                </div>

                {/* Results Section */}
                <AnimatePresence>
                    {result && (
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            className="glass-panel p-8 rounded-2xl border-l-4 border-neuro-500"
                        >
                            <h2 className="text-2xl font-bold text-white mb-6">Diagnostic Report</h2>

                            <div className="mb-8">
                                <p className="text-sm text-gray-400 mb-1">Detected Condition</p>
                                <div className="text-4xl font-mono text-neuro-300 font-bold tracking-tight">
                                    {result.diagnosis}
                                </div>
                            </div>

                            <div className="mb-8">
                                <div className="flex justify-between text-sm mb-2">
                                    <span className="text-gray-400">AI Confidence Score</span>
                                    <span className="text-white font-mono">{(result.confidence * 100).toFixed(2)}%</span>
                                </div>
                                <div className="h-4 bg-gray-800 rounded-full overflow-hidden">
                                    <motion.div
                                        initial={{ width: 0 }}
                                        animate={{ width: `${result.confidence * 100}%` }}
                                        transition={{ duration: 1, ease: "easeOut" }}
                                        className={`h-full ${getConfidenceColor(result.confidence)} relative`}
                                    >
                                        <div className="absolute inset-0 bg-white/20 animate-pulse"></div>
                                    </motion.div>
                                </div>
                            </div>

                            <div className="bg-dark-bg/50 p-4 rounded-xl border border-neuro-900">
                                <h3 className="text-white font-semibold mb-2 flex items-center gap-2">
                                    <AlertTriangle className="w-4 h-4 text-yellow-500" />
                                    Clinical Note
                                </h3>
                                <p className="text-sm text-gray-400 leading-relaxed">
                                    This result is generated by an AI model (ViT-Base) and should be verified by a certified radiologist.
                                    The confidence score indicates the model's certainty based on the training data.
                                </p>
                            </div>

                            <div className="mt-8 flex gap-4">
                                <button
                                    onClick={handleDownloadReport}
                                    className="flex-1 py-3 border border-neuro-700 hover:bg-neuro-900/50 rounded-lg text-neuro-400 transition-colors flex items-center justify-center gap-2"
                                >
                                    <Download className="w-4 h-4" />
                                    Download Report
                                </button>
                                <button
                                    onClick={handleSaveHistory}
                                    className="flex-1 py-3 bg-white/10 hover:bg-white/20 rounded-lg text-white transition-colors flex items-center justify-center gap-2"
                                >
                                    <Save className="w-4 h-4" />
                                    Save to Patient History
                                </button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
};

export default ScanPage;
